refactor: rename log as logger and replace more print
  File "C:\Git\Yuheng\tests\cases\../../src\yuheng\plugin\viz_folium\__main__.py", line 104, in display
    log.info(f"There are {len(kwargs)} object need to append")
    ^^^^^^^^
AttributeError: module 'yuheng.basic.log' has no attribute 'info'